name: pnlpipe3

channels:
  - conda-forge

dependencies:
  - python=3.6
  - ipython
  - plumbum
  - future
  - numpy
  - pandas
  - vtk
  - cmake
  - nibabel
  - nilearn
  - dipy
  - pyyaml
  - psutil
  - csvkit
  - cython
  - joblib
  - matplotlib
  - conda-build
  - luigi
  - sqlalchemy
  - dash
  - tensorflow==1.12.0
  - keras==2.2.4
  - git
  - pip
  - pip:
     - git+https://github.com/tashrifbillah/whitematteranalysis.git
     - git+https://github.com/dstrohl/Python_log_indenter.git
     - git+https://github.com/mhe/pynrrd.git
     - git+https://github.com/pnlbwh/conversion.git
