name: pnlpipe3-gpu

channels:
    - conda-forge

dependencies:
    - python
    - ipython

    - tensorflow-gpu==1.12.0
    - cudnn==7.6.0
    - keras==2.2.4
    - torchvision=0.8.2
    - h5py<3

    - nibabel
    - luigi
    - plumbum
    - sqlalchemy
    - psutil
    - pip

    - pip:
        - prompt-toolkit
        - gputil
        - scikit-image
        - SimpleITK
        - dipy==1.2.0
        - torch
        - git+https://github.com/pnlbwh/conversion.git
        - git+https://github.com/MIC-DKFZ/batchgenerators#egg=batchgenerators


